# 0.0. Setup

In [49]:
import os
import gc
import copy
import json
import requests
from pathlib import Path

import re
import pickle
import importlib
import numpy as np
import pandas as pd
import openpyxl as opxl
import matplotlib.pyplot as plt
from typing import Optional, Dict, Any, List

# None means 'no limit'
pd.set_option('display.max_columns', None)

PROJECT_DIR = Path.cwd().parent

DATA_DIR = PROJECT_DIR / 'data'
DATA_PUBLIC_DIR = PROJECT_DIR / 'data/public'
DATA_PRIVATE_DIR = PROJECT_DIR / 'data/private'
DATA_PROCESSED_DIR = PROJECT_DIR / 'data/processed'
OUTPUT_DIR = PROJECT_DIR / 'output'

# 1.0. Load data

In [2]:
!ls '{DATA_PRIVATE_DIR}'

'2024-2025 GASTPE Participating Schools Top-up Data.xlsx'
 Alphalist-Schools-Slots-addon_slots.csv
 Alphalist-Schools-Slots-fixed_slots.csv
 Alphalist-Schools-Slots-incentive_slots.csv
 ESC
'ESC and SHSVP Tuition.xlsx'
'GASTPE Yearend Report SY 24-25 (Certfication Annexes).pdf'
'Private School Seats and TOSF ao 2025Oct27.xlsx'
 SHSVP
'SUMMARY OF PRIVATE SCHOOL PROFILE.xlsx'
'SY 23-24 ESC Slots as of 020426.xlsx'
 gastpe_certification_annexes_sy2425.csv
 priv_classroom_furniture.xlsx
 raw_validation_sheets
'~$SY 23-24 ESC Slots as of 020426.xlsx'

In [3]:
fnames = [fn for fn in os.listdir(DATA_PRIVATE_DIR) if re.search(r'alphalist-schools', fn, flags=re.IGNORECASE)]
fpaths = [os.path.join(DATA_PRIVATE_DIR, fn) for fn in fnames]
display(fpaths)

['/workspace/project_paaral/data/private/Alphalist-Schools-Slots-addon_slots.csv',
 '/workspace/project_paaral/data/private/Alphalist-Schools-Slots-fixed_slots.csv',
 '/workspace/project_paaral/data/private/Alphalist-Schools-Slots-incentive_slots.csv']

## 1.1. Read all

In [4]:
dfs = []
for fpath in fpaths:
    df = pd.read_csv(fpath)
    dfs.append(df)

## 1.2. Inspect

In [5]:
print(dfs[0].shape)
display(dfs[0].head(2))
display(dfs[0].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.      0
1    1104375  Newfoundland Arts and Science Academy of Tagum...      0

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.      0
4549    1704253  Southwestern Institute of Business and Technol...      0

In [6]:
print(dfs[1].shape)
display(dfs[1].head(2))
display(dfs[1].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.     38
1    1104375  Newfoundland Arts and Science Academy of Tagum...     50

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.     11
4549    1704253  Southwestern Institute of Business and Technol...     50

In [7]:
print(dfs[2].shape)
display(dfs[2].head(2))
display(dfs[2].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.      0
1    1104375  Newfoundland Arts and Science Academy of Tagum...      0

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.      0
4549    1704253  Southwestern Institute of Business and Technol...      0

# 2.0. Process

## 2.1. Aggregate slots

In [8]:
dfs_tmp = copy.copy(dfs)

csv_label = [
    'addon',
    'fixed',
    'incentive'
]

dfs_processed = []
for df, label in zip(dfs_tmp, csv_label):
    df['School ID'] = df['School ID'].astype(str)
    df['Value'] = df['Value'].astype(int)
    
    new_columns = ['esc_school_id','school_name','count']
    df.columns = new_columns
    df.rename(
        columns={
            'count':'count_'+label+'_slots'
        }, inplace=True
    )
    df.set_index(df.columns[0], inplace=True)
    df.drop(columns='school_name', inplace=True)

    dfs_processed.append(df)

dfs_processed = pd.concat(dfs_processed, axis=1)
dfs_processed['total_count_slots'] = dfs_processed.sum(axis=1)

print(dfs_processed.shape)

(4550, 4)

In [9]:
dfs_processed

,count_addon_slots,count_fixed_slots,count_incentive_slots,total_count_slots
esc_school_id,,,,
303929,0,38,0,38
1104375,0,50,0,50
1504390,44,50,0,94
304395,0,50,0,50
1404408,0,50,0,50
...,...,...,...,...
1704000,0,0,0,0
1704001,0,12,0,12
1704002,10,50,0,60
1704003,0,11,0,11
1704253,0,50,0,50

## 2.2. Match ESC IDs

In [10]:
# We'll use the GASTPE dataset to make a DepEd-PEAC school id match
fpath = os.path.join(DATA_PRIVATE_DIR, 'ESC and SHSVP Tuition.xlsx')
gastpe_excel = pd.read_excel(fpath, sheet_name='Tuition', engine='calamine')
print(gastpe_excel.shape)

(5188, 15)

In [11]:
display(gastpe_excel.head(2))

,Region SHS,Program,SUC/LUC,Billed in SY 2024-2025 (ESC),ESC School ID,DepEd School Id,School Name,ESC (Tuition),ESC (Other),ESC (Misc),ESC (Total),SHSVP (Tuition),SHSVP (Other),SHSVP (Misc),SHSVP (Total)
0,Region I,BOTH,NaN,NaN,100008.0,400001,"St. Andrew Academy of Bacarra, Inc.",13353.05,3817.85,2220.0,19390.90,15515.0,3210.0,2220.0,20945.0
1,Region I,BOTH,NaN,NaN,100018.0,400002,"Badoc Junior College, Inc.",9808.26,908.98,0.0,10717.24,15000.0,2658.0,0.0,17658.0

### Process

In [12]:
essential_columns = ['DepEd School Id','ESC School ID']
df_tmp = gastpe_excel[essential_columns].copy()

new_columns = ['school_id','esc_school_id']
df_tmp.columns = new_columns

# ESC School ID columns has NaNs that is why its float
for col in df_tmp.columns:
    df_tmp[col] = df_tmp[col].astype(str)

mask_na = df_tmp['esc_school_id'].str.contains(r'nan', flags=re.IGNORECASE)
df_tmp.loc[~mask_na, 'esc_school_id'] = df_tmp.loc[~mask_na, 'esc_school_id'].apply(lambda x: re.findall(r'(.*).0', x)[0])
df_tmp.loc[mask_na, 'esc_school_id'] = 'No ESC School ID'

print(df_tmp.shape)

# Create dictionary of ESC-DepEd school ID pairs
deped_esc_ids = {k:v for k,v in zip(df_tmp['school_id'], df_tmp['esc_school_id'])}
esc_deped_ids = {v:k for k,v in deped_esc_ids.items()}

(5188, 2)

In [48]:
# Uncomment to inspect
display(deped_esc_ids)

{'400001': '100008',
 '400002': '100018',
 '400003': '100023',
 '400004': '100025',
 '400006': '100013',
 '400007': '100020',
 '400008': '100021',
 '400010': '100024',
 '400011': '103753',
 '400012': '100028',
 '400013': '100019',
 '400015': '100012',
 '400016': '100026',
 '400017': '100006',
 '400018': '100010',
 '400019': '100007',
 '400020': '100009',
 '400021': '100027',
 '400022': '100029',
 '400023': '100017',
 '400025': '100015',
 '400026': '100016',
 '400027': '100034',
 '400028': '100040',
 '400029': '100031',
 '400031': '100047',
 '400032': '100045',
 '400035': '100039',
 '400036': '100038',
 '400037': '100035',
 '400039': '100042',
 '400040': '100057',
 '400043': '100036',
 '400044': '100052',
 '400045': '100037',
 '400046': '100043',
 '400047': '100044',
 '400048': '100050',
 '400049': '100051',
 '400050': '100053',
 '400051': '100054',
 '400052': '100048',
 '400053': '100055',
 '400054': '100056',
 '400055': '100030',
 '400056': '100046',
 '400061': '100032',
 '400062': '100033',
 '400067': '100078',
 '400068': '100079',
 '400070': '100089',
 '400072': '100080',
 '400073': '100085',
 '400075': '103238',
 '400076': '103147',
 '400077': 'No ESC School ID',
 '400078': '100075',
 '400080': '100067',
 '400081': '100072',
 '400082': '100068',
 '400084': '100083',
 '400085': '100087',
 '400086': '103146',
 '400090': '100084',
 '400091': '102858',
 '400092': '100073',
 '400097': '100086',
 '400098': '100090',
 '400101': '100059',
 '400103': '100061',
 '400104': '100060',
 '400105': '100062',
 '400106': '102598',
 '400107': '100063',
 '400110': '100064',
 '400112': '100065',
 '400115': '100069',
 '400119': '100076',
 '400120': '104372',
 '400121': '100071',
 '400124': '100088',
 '400125': '100091',
 '400128': '100104',
 '400129': '100115',
 '400136': '100101',
 '400138': '100098',
 '400139': '100094',
 '400140': '100102',
 '400142': '103256',
 '400145': '100125',
 '400146': '100105',
 '400149': '103151',
 '400151': '104364',
 '400153': '100109',
 '400154': '104071',
 '400156': '100096',
 '400157': '100097',
 '400158': '100100',
 '400159': '100111',
 '400160': '100112',
 '400168': '101951',
 '400169': '100110',
 '400170': '100099',
 '400173': '100117',
 '400174': '100118',
 '400175': '100122',
 '400176': '100106',
 '400177': '100107',
 '400179': '103525',
 '400180': '100119',
 '400181': '102859',
 '400186': '100114',
 '400195': '103417',
 '400199': '100146',
 '400202': '104080',
 '400203': '100133',
 '400204': '103876',
 '400206': '100138',
 '400208': '102600',
 '400210': '103218',
 '400212': '100137',
 '400213': '100142',
 '400215': '103413',
 '400218': '100156',
 '400225': '100130',
 '400227': '100135',
 '400229': '102601',
 '400230': '100141',
 '400231': '100164',
 '400234': '100163',
 '400235': '100166',
 '400236': '100165',
 '400238': '100150',
 '400239': '100151',
 '400240': '100160',
 '400243': '103535',
 '400245': '100159',
 '400246': '100162',
 '400249': '100154',
 '400252': 'No ESC School ID',
 '400253': '100131',
 '400254': 'No ESC School ID',
 '400255': '101952',
 '400256': '103253',
 '400258': '103406',
 '400259': '100132',
 '400260': '100134',
 '400263': '103330',
 '400265': '100143',
 '400266': '100136',
 '400267': '103411',
 '400269': '101953',
 '400270': '100139',
 '400271': '100140',
 '400274': '103536',
 '400277': '100002',
 '400278': '100003',
 '400285': '100004',
 '400287': '100005',
 '400288': '103534',
 '400291': '100011',
 '400297': '102951',
 '400298': '103408',
 '400300': '103528',
 '400303': '103923',
 '400304': 'No ESC School ID',
 '400306': '100126',
 '400307': '103258',
 '400308': '100129',
 '400309': '100123',
 '400310': '100128',
 '400311': '100124',
 '400312': '100127',
 '400315': '103752',
 '400316': '102857',
 '400318': '100149',
 '400319': '102952',
 '400321': '103410',
 '400324': '102953',
 '400325': '100152',
 '400326': '103416',
 '400331': '200184',
 '400332': '202605',
 '400334': '200169',
 '400335': '200181',
 '400336': '200183',
 '400339': '200203',
 '400344': '200168',
 '400345': '200170',
 '400349': '200180',
 '400350': '200179',
 '400353': '200190',
 '400354': '200194',
 '400356': '200173',
 '400357': '200188',
 '400360': '200171',
 '400361': '200199',
 '400362': '200182',
 '400364': '200202',
 '400366': '200174',
 '400368': '200177',
 '400370': '200175',
 '400375': '200172',
 '400377': '200187',
 '400378': '200197',
 '400379': '200192',
 '400382': '203933',
 '400383': '200191',
 '400384': '200193',
 '400385': '200196',
 '400386': '200185',
 '400387': '200189',
 '400389': '200198',
 '400391': '200176',
 '400392': '200178',
 '400394': '200204',
 '400399': '200201',
 '400400': '203290',
 '400404': '200222',
 '400406': '200227',
 '400407': '200230',
 '400410': '200215',
 '400412': '200219',
 '400414': '200211',
 '400416': '200225',
 '400417': '202673',
 '400418': '201962',
 '400420': '203927',
 '400422': '200224',
 '400423': '201964',
 '400424': '201965',
 '400426': '200228',
 '400429': '200241',
 '400431': '200242',
 '400432': '200240',
 '400435': '201960',
 '400436': '200207',
 '400440': '200212',
 '400443': '200232',
 '400444': '200236',
 '400446': '200208',
 '400448': '203537',
 '400450': '200220',
 '400452': '200216',
 '400453': '200235',
 '400454': '200237',
 '400455': '200217',
 '400457': '200239',
 '400458': '200231',
 '400459': '200214',
 '400460': '200223',
 '400462': '200226',
 '400464': '200234',
 '400470': '200238',
 '400475': '200243',
 '400476': '200210',
 '400477': '200213',
 '400483': '200249',
 '400484': '200257',
 '400485': '200246',
 '400491': '200252',
 '400499': '200251',
 '400506': '200256',
 '400509': '200253',
 '400515': '200258',
 '400517': '200255',
 '400520': '200247',
 '400521': '200244',
 '400532': '200254',
 '400536': '200250',
 '400540': '200260',
 '400543': '200261',
 '400546': '200262',
 '400548': '200200',
 '400555': 'No ESC School ID',
 '400561': '200206',
 '400562': '200205',
 '400568': '300263',
 '400571': '300265',
 '400574': '300266',
 '400578': '300269',
 '400579': '300264',
 '400581': '300267',
 '400584': '300270',
 '400586': '300268',
 '400591': '1301760',
 '400593': '303539',
 '400603': '301983',
 '400609': '1004362',
 '400610': '300275',
 '400615': '303556',
 '400616': '300276',
 '400619': '303578',
 '400621': '301977',
 '400623': '301978',
 '400624': '303930',
 '400626': '303931',
 '400628': '303103',
 '400630': '303779',
 '400631': '300272',
 '400632': '300273',
 '400634': '301973',
 '400638': '300277',
 '400643': '300278',
 '400644': '301976',
 '400646': '300274',
 '400648': '301996',
 '400649': '300310',
 '400650': '302918',
 '400651': '300312',
 '400656': '303156',
 '400657': '301987',
 '400661': '300295',
 '400664': '300300',
 '400668': '304184',
 '400669': '300292',
 '400673': '302008',
 '400676': '302615',
 '400678': '301991',
 '400679': '300302',
 '400680': '303126',
 '400683': '300304',
 '400685': '303489',
 '400688': '303315',
 '400689': '303038',
 '400690': '300308',
 '400700': '301988',
 '400701': '300294',
 '400703': '303932',
 '400704': '301990',
 '400708': '301994',
 '400710': '303293',
 '400711': '301995',
 '400712': '302940',
 '400713': '300279',
 '400714': '303130',
 '400715': 'No ESC School ID',
 '400716': '303269',
 '400717': '300281',
 '400722': '303137',
 '400723': '300297',
 '400724': '300303',
 '400725': '301993',
 '400729': '300280',
 '400730': 'No ESC School ID',
 '400735': '302618',
 '400736': '302620',
 '400739': '303301',
 '400742': '303559',
 '400744': '300299',
 '400750': '303487',
 '400751': '303978',
 '400753': '303576',
 '400754': '303935',
 '400758': '300286',
 '400759': '300289',
 '400763': '302610',
 '400765': 'No ESC School ID',
 '400768': '303044',
 '400771': '303333',
 '400773': '303334',
 '400775': '303043',
 '400778': '1201700',
 '400779': '1203212',
 '400780': '303769',
 '400784': '303312',
 '400786': 'No ESC School ID',
 '400788': '1004035',
 '400792': '1002999',
 '400793': '1001405',
 '400795': '300290',
 '400801': '302005',
 '400804': '402300',
 '400806': '303335',
 '400808': '304335',
 '400809': '303091',
 '400810': '304309',
 '400811': '304206',
 '400815': '404173',
 '400816': '303484',
 '400819': '303205',
 '400820': '403291',
 '400823': '302020',
 '400824': '303247',
 '400826': '304164',
 '400828': '403668',
 '400830': '203929',
 '400831': '303562',
 '400834': '1301759',
 '400836': '303096',
 '400839': '300326',
 '400842': '302016',
 '400844': 'No ESC School ID',
 '400845': '302022',
 '400849': '303284',
 '400853': '300329',
 '400854': '300331',
 '400855': '300332',
 '400857': 'No ESC School ID',
 '400858': '304459',
 '400859': '300336',
 '400860': 'No ESC School ID',
 '400861': 'No ESC School ID',
 '400862': '300314',
 '400864': '303336',
 '400865': '300322',
 '400867': 'No ESC School ID',
 '400868': '303139',
 '400869': 'No ESC School ID',
 '400871': '303206',
 '400874': '300293',
 '400875': 'No ESC School ID',
 '400876': '300296',
 '400877': '300298',
 '400880': '300285',
 '400883': 'No ESC School ID',
 '400885': 'No ESC School ID',
 '400889': 'No ESC School ID',
 '400890': '303776',
 '400894': '300306',
 '400898': '302813',
 '400899': '300307',
 '400901': '304161',
 '400906': 'No ESC School ID',
 '400908': '300284',
 '400909': '303127',
 '400912': 'No ESC School ID',
 '400914': '300287',
 '400916': '300311',
 '400918': '303982',
 '400920': '300313',
 '400922': '300316',
 '400925': 'No ESC School ID',
 '400927': 'No ESC School ID',
 '400928': '300315',
 '400929': '303210',
 '400930': '300317',
 '400934': '303033',
 '400935': '301997',
 '400936': '300318',
 '400937': '303764',
 '400938': '303574',
 '400941': '303756',
 '400942': 'No ESC School ID',
 '400945': '300323',
 '400950': '302009',
 '400951': 'No ESC School ID',
 '400954': '303554',
 '400956': '303941',
 '400958': '302011',
 '400959': 'No ESC School ID',
 '400961': '302013',
 '400963': '303768',
 '400964': '303942',
 '400965': '302015',
 '400967': 'No ESC School ID',
 '400969': '300327',
 '400970': '303090',
 '400975': '303053',
 '400977': '303940',
 '400978': 'No ESC School ID',
 '400982': '300356',
 '400985': '303343',
 '400989': '302619',
 '400992': '300345',
 '400997': 'No ESC School ID',
 '400999': 'No ESC School ID',
 '401000': 'No ESC School ID',
 '401002': '302037',
 '401003': '300373',
 '401005': '300339',
 '401007': '300360',
 '401008': '300342',
 '401009': '302035',
 '401010': '300371',
 '401011': '300365',
 '401012': '300344',
 '401013': '302029',
 '401016': 'No ESC School ID',
 '401018': '300350',
 '401024': '300354',
 '401026': '300340',
 '401027': 'No ESC School ID',
 '401029': '300351',
 '401032': '303946',
 '401033': '300341',
 '401034': 'No ESC School ID',
 '401035': '300349',
 '401041': '300370',
 '401042': '303220',
 '401043': '303051',
 '401044': '300369',
 '401046': '302922',
 '401047': '303482',
 '401050': '302028',
 '401053': '302763',
 '401059': 'No ESC School ID',
 '401060': 'No ESC School ID',
 '401062': '303762',
 '401063': '300352',
 '401064': '302030',
 '401067': 'No ESC School ID',
 '401068': 'No ESC School ID',
 '401070': '303296',
 '401072': '300358',
 '401076': '303099',
 '401077': '300364',
 '401078': '300338',
 '401081': '300343',
 '401089': '300347',
 '401094': '300346',
 '401096': '303551',
 '401101': '300400',
 '401102': 'No ESC School ID',
 '401105': '300417',
 '401106': '300399',
 '401107': '300401',
 '401108': '303949',
 '401112': '300413',
 '401114': 'No ESC School ID',
 '401116': '303765',
 '401118': '300386',
 '401120': '300391',
 '401121': '300394',
 '401124': '300387',
 '401125': '303286',
 '401129': '303950',
 '401131': '300395',
 '401133': '303209',
 '401136': '300388',
 '401137': '300389',
 '401138': '303052',
 '401139': '300390',
 '401140': '300393',
 '401141': 'No ESC School ID',
 '401142': '300396',
 '401143': 'No ESC School ID',
 '401144': 'No ESC School ID',
 '401145': '300374',
 '401147': '303477',
 '401150': 'No ESC School ID',
 '401151': 'No ESC School ID',
 '401152': '300379',
 '401155': '303285',
 '401159': '303490',
 '401160': 'No ESC School ID',
 '401161': '300383',
 '401164': '300411',
 '401165': '303347',
 '401167': '303546',
 '401168': 'No ESC School ID',
 '401169': '302055',
 '401170': '300380',
 '401171': '303773',
 '401172': '300408',
 '401173': '300412',
 '401174': '300418',
 '401178': '303479',
 '401180': '303061',
 '401182': 'No ESC School ID',
 '401183': '300404',
 '401185': '300409',
 '401187': 'No ESC School ID',
 '401189': '303485',
 '401192': '300406',
 '401193': 'No ESC School ID',
 '401194': '300410',
 '401195': 'No ESC School ID',
 '401196': '300414',
 '401198': '300402',
 '401199': '303228',
 '401201': '300398',
 '401205': '303348',
 '401206': '300397',
 '401208': '300455',
 '401209': '302608',
 '401210': '303128',
 '401211': '300419',
 '401212': '300420',
 '401216': '300453',
 '401218': '302051',
 '401220': '300452',
 '401222': '302994',
 '401223': '300440',
 '401224': '300442',
 '401228': '300444',
 '401232': '300454',
 '401233': '302614',
 '401234': 'No ESC School ID',
 '401236': '300427',
 '401237': 'No ESC School ID',
 '401239': '300428',
 '401242': 'No ESC School ID',
 '401243': '302609',
 '401245': '300423',
 '401246': '300422',
 '401248': '300425',
 '401249': '310438',
 '401250': '300430',
 '401251': '300434',
 '401252': '300435',
 '401253': '300436',
 '401254': '300433',
 '401255': '300437',
 '401260': '300438',
 '401261': '300439',
 '401262': '300443',
 '401263': '303025',
 '401268': '300474',
 '401269': '300464',
 '401270': '300471',
 '401271': '300461',
 '401276': '300469',
 '401277': '300467',
 '401278': '300472',
 '401279': '300463',
 '401280': '300468',
 '401281': '300465',
 '401282': '300475',
 '401283': '300470',
 '401284': '300477',
 '401285': '300462',
 '401286': '300466',
 '401287': '300476',
 '401288': 'No ESC School ID',
 '401289': '300473',
 '401290': 'No ESC School ID',
 '401292': '300459',
 '401293': 'No ESC School ID',
 '401294': '300460',
 '401295': 'No ESC School ID',
 '401302': '302038',
 '401306': '302039',
 '401317': '300377',
 '401318': '303321',
 '401321': 'No ESC School ID',
 '401322': '300378',
 '401324': 'No ESC School ID',
 '401325': 'No ESC School ID',
 '401326': '302995',
 '401329': 'No ESC School ID',
 '401330': '300381',
 '401331': '302042',
 '401332': 'No ESC School ID',
 '401333': 'No ESC School ID',
 '401335': '302043',
 '401336': '300382',
 '401343': '300385',
 '401348': '300357',
 '401356': '300359',
 '401357': '304373',
 '401359': '303882',
 '401360': 'No ESC School ID',
 '401361': '300361',
 '401363': '302033',
 '401364': '300366',
 '401365': '300367',
 '401368': '300456',
 '401370': '300457',
 '401371': '303095',
 '401372': 'No ESC School ID',
 '401375': '302053',
 '401381': '303565',
 '401385': '300458',
 '401386': '303881',
 '401387': 'No ESC School ID',
 '401391': '301998',
 '401393': 'No ESC School ID',
 '401397': 'No ESC School ID',
 '401399': '300319',
 '401400': '302611',
 '401403': '302001',
 '401404': '300320',
 '401405': '1404236',
 '401406': '302002',
 '401407': '302613',
 '401408': '300321',
 '401412': 'No ESC School ID',
 '401414': 'No ESC School ID',
 '401415': '300324',
 '401417': '302007',
 '401421': 'No ESC School ID',
 '401429': 'No ESC School ID',
 '401431': '300325',
 '401434': 'No ESC School ID',
 '401435': '302616',
 '401437': '303207',
 '401439': '302012',
 '401440': 'No ESC School ID',
 '401442': 'No ESC School ID',
 '401445': 'No ESC School ID',
 '401446': '302014',
 '401447': 'No ESC School ID',
 '401448': 'No ESC School ID',
 '401451': 'No ESC School ID',
 '401453': 'No ESC School ID',
 '401454': '302017',
 '401455': 'No ESC School ID',
 '401456': '302018',
 '401457': 'No ESC School ID',
 '401459': 'No ESC School ID',
 '401460': '302023',
 '401462': '302939',
 '401463': '302617',
 '401464': '302025',
 '401467': '300335',
 '401470': '303944',
 '401473': 'No ESC School ID',
 '401474': 'No ESC School ID',
 '401476': '303029',
 '401481': '300333',
 '401486': 'No ESC School ID',
 '401487': '303774',
 '401489': '302027',
 '401493': 'No ESC School ID',
 '401495': 'No ESC School ID',
 '401499': '303951',
 '401500': 'No ESC School ID',
 '401502': '303759',
 '401507': '302045',
 '401513': 'No ESC School ID',
 '401515': '303488',
 '401517': '303561',
 '401518': '303054',
 '401519': '300368',
 '401520': 'No ESC School ID',
 '401524': '303775',
 '401527': 'No ESC School ID',
 '401528': '302049',
 '401530': '303478',
 '401531': 'No ESC School ID',
 '401533': '303980',
 '401534': '300445',
 '401535': '300446',
 '401539': '300449',
 '401543': '300450',
 '401544': 'No ESC School ID',
 '401545': '303761',
 '401546': '303955',
 '401547': '302992',
 '401548': '302993',
 '401549': '400504',
 '401551': 'No ESC School ID',
 '401552': '400515',
 '401553': 'No ESC School ID',
 '401554': '400506',
 '401555': '400507',
 '401556': 'No ESC School ID',
 '401561': '400484',
 '401565': '403167',
 '401568': '400516',
 '401570': '400496',
 '401574': '402224',
 '401577': '400479',
 '401579': 'No ESC School ID',
 '401580': '403842',
 '401581': '400480',
 '401582': '400489',
 '401583': '404181',
 '401585': '403956',
 '401586': '404502',
 '401589': '400536',
 '401591': '403695',
 '401595': '400495',
 '401597': '400486',
 '401598': '400493',
 '401599': '400494',
 '401602': '400499',
 '401603': '403697',
 '401608': '400500',
 '401609': '400502',
 '401612': '400509',
 '401615': '400510',
 '401617': '403436',
 '401619': 'No ESC School ID',
 '401622': '400481',
 '401624': 'No ESC School ID',
 '401629': '400526',
 '401630': '400527',
 '401636': '400534',
 '401638': '402236',
 '401639': '404088',
 '401640': '400539',
 '401641': '400541',
 '401644': '402234',
 '401645': '400532',
 '401646': '400537',
 '401647': '400521',
 '401650': '400528',
 '401654': '400501',
 '401656': '400503',
 '401661': '403275',
 '401662': '402226',
 '401663': '403369',
 '401665': '404257',
 '401667': '402231',
 '401673': '402212',
 '401674': '400492',
 '401679': '400517',
 '401680': '400519',
 '401681': '400520',
 '401684': '403959',
 '401686': '402228',
 '401687': '403370',
 '401688': 'No ESC School ID',
 '401689': '403371',
 '401692': '400513',
 '401693': '402230',
 '401696': 'No ESC School ID',
 '401698': '402232',
 '401701': '400533',
 '401702': '400542',
 '401703': '400482',
 '401704': '400490',
 '401707': '403960',
 '401711': '400569',
 '401712': '403438',
 '401713': '400573',
 '401722': '403637',
 '401729': 'No ESC School ID',
 '401731': 'No ESC School ID',
 '401732': 'No ESC School ID',
 '401734': 'No ESC School ID',
 '401735': '403961',
 '401742': '400543',
 '401743': 'No ESC School ID',
 '401748': '403652',
 '401750': '403653',
 '401751': 'No ESC School ID',
 '401755': 'No ESC School ID',
 '401756': 'No ESC School ID',
 '401762': '402239',
 '401763': 'No ESC School ID',
 '401768': 'No ESC School ID',
 '401777': 'No ESC School ID',
 '401782': 'No ESC School ID',
 '401783': 'No ESC School ID',
 '401785': 'No ESC School ID',
 '401788': '402982',
 '401795': '403675',
 '401799': 'No ESC School ID',
 '401800': 'No ESC School ID',
 '401806': 'No ESC School ID',
 '401809': 'No ESC School ID',
 '401812': '402241',
 '401818': 'No ESC School ID',
 '401821': 'No ESC School ID',
 '401823': 'No ESC School ID',
 '401824': 'No ESC School ID',
 '401826': '400547',
 '401828': 'No ESC School ID',
 '401829': 'No ESC School ID',
 '401833': '403846',
 '401834': '403849',
 '401836': '402243',
 '401840': '402553',
 '401842': '402244',
 '401844': 'No ESC School ID',
 '401845': '402554',
 '401848': '402245',
 '401853': '404067',
 '401854': 'No ESC School ID',
 '401855': 'No ESC School ID',
 '401858': '400550',
 '401859': 'No ESC School ID',
 '401860': '402248',
 '401861': '400551',
 '401863': 'No ESC School ID',
 '401864': 'No ESC School ID',
 '401866': 'No ESC School ID',
 '401871': 'No ESC School ID',
 '401872': 'No ESC School ID',
 '401873': 'No ESC School ID',
 '401876': 'No ESC School ID',
 '401878': 'No ESC School ID',
 '401883': 'No ESC School ID',
 '401884': '404337',
 '401887': '400553',
 '401888': '403419',
 '401889': 'No ESC School ID',
 '401892': '403641',
 '401900': 'No ESC School ID',
 '401902': 'No ESC School ID',

### Match

In [14]:
dfs_processed.index.map(esc_deped_ids)

Index(['418013', '408365', '406245', '419005',      nan, '404601', '446545',
       '401884', '406004', '400609',
       ...
       '403425', '403514', '403533', '430502', '430016',      nan, '408013',
       '403391', '407742', '406959'],
      dtype='object', name='esc_school_id', length=4550)

In [15]:
df_match = dfs_processed.copy()
df_match['school_id'] = df_match.index.map(esc_deped_ids)
df_match['school_id'] = df_match['school_id'].astype(str)

df_match['has_deped_school_id'] = None
mask = df_match['school_id'] == 'nan'
df_match.loc[mask, 'has_deped_school_id'] = False
df_match.loc[~mask, 'has_deped_school_id'] = True

df_match.reset_index(inplace=True)
print(df_match.shape)

(4550, 7)

In [16]:
df_match['has_deped_school_id'].sum()

3621

Note: There are ESC schools that did **not** exist yet in SY 2023-2024 hence the False values in `has_deped_school_id`.

In [17]:
display(df_match)

,esc_school_id,count_addon_slots,count_fixed_slots,count_incentive_slots,total_count_slots,school_id,has_deped_school_id
0,303929,0,38,0,38,418013,True
1,1104375,0,50,0,50,408365,True
2,1504390,44,50,0,94,406245,True
3,304395,0,50,0,50,419005,True
4,1404408,0,50,0,50,nan,False
...,...,...,...,...,...,...,...
4545,1704000,0,0,0,0,nan,False
4546,1704001,0,12,0,12,408013,True
4547,1704002,10,50,0,60,403391,True
4548,1704003,0,11,0,11,407742,True
4549,1704253,0,50,0,50,406959,True

# 3.0. Unutilized slots
(Feb 4, 2026) ECAIR received data from GASS on official unutilized slots of ESC delivering schools in SY 2023-2024.

## 3.1. Load

In [18]:
fname = "SY 23-24 ESC Slots as of 020426.xlsx"
fpath = str(DATA_PRIVATE_DIR / fname)
esc_until = pd.read_excel(fpath, sheet_name='SUMMARY')
print(esc_until.shape)

(4640, 18)

In [20]:
display(esc_until.head(2))
display(esc_until.tail(2))

,School ID,School Name,Unnamed: 2,VALUE,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,School ID.1,School Name.1,Unnamed: 12,VALUE.1,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,FIXED,INCENTIVE,ADDITIONAL,TOTAL SLOT,BILLED,UNUTILIZED SLOTS,NaN,NaN,NaN,NaN,FIXED,INCENTIVE,ADDITIONAL,TOTAL SLOT,BILLED,UNUTILIZED SLOTS
1,303929.0,"One La Salle Educational Foundation, Inc.",38,0,0,38,32,6,NaN,NaN,903459,"Sibugay Technical Institute, Inc.",191,0,0,191,0,191

,School ID,School Name,Unnamed: 2,VALUE,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,School ID.1,School Name.1,Unnamed: 12,VALUE.1,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
4638,1704253.0,Southwestern Institute of Business and Technol...,50,0,0,50,39,11,NaN,NaN,701220,University of San Carlos (South Campus),202,0,15,217,310,-93
4639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL,NaN,239956,0,52351,292307,226483,65824

## 3.2. Clean

In [43]:
tmp = esc_until.copy()
half_headers = [
    'esc_school_id','school_name',
    'slots_fixed','slots_incentive',
    'slots_additional','slots_total',
    'slots_billed','slots_unutilized',
]

half_idxs = [(0,8), (10,18)]

halves = []
for i, tup_idx in enumerate(half_idxs):
    half_a = tmp.iloc[1:,tup_idx[0]:tup_idx[1]]
    half_a.columns = half_headers
    
    # Drop rows whose school id is Nan
    half_a = half_a.dropna(subset='esc_school_id')
    
    # Establish data types
    for col in ['esc_school_id','school_name']:
        half_a[col] = half_a[col].astype(str)
    
    for col in half_a.loc[:,"slots_fixed":].columns:
        half_a[col] = half_a[col].astype(int)

    # Only the first half has school IDs that have a decimal
    if i == 0:
        # Clean esc school ids
        pattern = r"(.*)\.0"
        half_a['esc_school_id'] = half_a['esc_school_id'].str.extract(pattern)
    elif i == 1:
        half_a = half_a.iloc[:-1,:]  # Remove TOTAL row
    
    # display(half_a.head())
    halves.append(half_a)
    # break

halves = pd.concat(halves, axis=0, ignore_index=True)
print(halves.shape)

# I don't trust slots_unutilized so I will recompute
halves['slots_total_minus_billed'] = halves['slots_total'] - halves['slots_billed']

(9276, 8)

## 3.3. Inspect

In [46]:
display(halves.head())

,esc_school_id,school_name,slots_fixed,slots_incentive,slots_additional,slots_total,slots_billed,slots_unutilized,slots_total_minus_billed
0,303929,"One La Salle Educational Foundation, Inc.",38,0,0,38,32,6,6
1,1104375,Newfoundland Arts and Science Academy of Tagum...,50,0,0,50,23,27,27
2,1504390,4th Watch Maranatha Christian Academy of Bagui...,50,0,44,94,27,67,67
3,304395,ADVENT SCHOOL FOUNDATION INC.,50,0,0,50,20,30,30
4,304350,"ASKI Skills and Knowledge Institute, Inc.",50,0,0,50,50,0,0

In [45]:
# Check if I just have trust issues
display(halves[halves['slots_total_minus_billed'] != halves['slots_unutilized']])

Empty DataFrame
Columns: [esc_school_id, school_name, slots_fixed, slots_incentive, slots_additional, slots_total, slots_billed, slots_unutilized, slots_total_minus_billed]
Index: []

## 3.4. DepEd IDs

In [68]:
# We (again) use our ESC Beneficiary datasets to get ESC-DepEd ID pairs
fname = "processed_esc_beneficiaries.parquet"
fpath = str(OUTPUT_DIR / fname)
benef = pd.read_parquet(fpath, engine='fastparquet')
# print(benef.shape)

# Process
benef_ids = benef[['esc_school_id', 'destination_school_id']].copy()

# Drop duplicating esc_school_id to make a table with unique esc schools
benef_ids = benef_ids.drop_duplicates(subset='esc_school_id')

for col in benef_ids.columns:
    benef_ids[col] = benef_ids[col].astype(str)

print(benef_ids.shape)

# Make a lookup dictionary
esc_deped_dict = benef_ids.set_index('esc_school_id').to_dict()

# Remove very heavy benef object from memory
del benef

(3767, 2)

In [52]:
display(benef_ids.head(2))

    esc_school_id destination_school_id
0         1603520                475511
611       1202204                405799

In [55]:
esc_deped_dict.keys()

dict_keys(['destination_school_id'])

In [72]:
mrg_halves = halves.copy()

mrg_halves['school_id'] = mrg_halves['esc_school_id'].map(esc_deped_dict['destination_school_id'])
# print(mrg_halves.shape)

# Tag esc school IDs with no DepEd ID counterpart
mrg_halves['has_deped_school_id'] = True
mask_na = mrg_halves['school_id'].isna()
mrg_halves.loc[mask_na, 'has_deped_school_id'] = False

# Rearrange columns
ord_cols = [
    'school_id', 'esc_school_id', 'school_name',
    'slots_total', 'slots_unutilized',
    'has_deped_school_id'
]
mrg_halves = mrg_halves[ord_cols]

print(mrg_halves.shape)

(9276, 6)

In [73]:
display(mrg_halves.isna().sum())

school_id              1742
esc_school_id             0
school_name               0
slots_total               0
slots_unutilized          0
has_deped_school_id       0
dtype: int64

### Inspect no IDs

In [74]:
display(
    mrg_halves[mrg_halves['school_id'].isna()]
)

,school_id,esc_school_id,school_name,slots_total,slots_unutilized,has_deped_school_id
14,NaN,304358,Discovery Child Development of Montessori Inc.,50,50,False
18,NaN,1404397,"Ingenium School, Inc",50,50,False
48,NaN,1404383,"Southville International School and Colleges, ...",50,41,False
68,NaN,1404387,"Philippine Cultural College, Inc",50,50,False
69,NaN,1404417,"Philippine Cultural College, Inc",50,50,False
...,...,...,...,...,...,...
8752,NaN,1702400,Center for Positive Futures,0,0,False
8753,NaN,1702403,Puerto Princesa Adventist Elementary School,0,0,False
8755,NaN,1702622,Fullbright College Integrated School,0,0,False
8756,NaN,1703707,Southfields Educational Foundation Philippines...,0,0,False
8757,NaN,1704000,"St. Anthony College Calapan City, Inc.",0,0,False

# 4.0. Save
Previously, we save the output of section 2. Now, as of Feb. 4, 2026, we save the output of Section 3.

In [75]:
fpath = str(OUTPUT_DIR / 'processed_esc_slots.parquet')
mrg_halves.to_parquet(fpath)
print(f"Saving successful!")

Saving successful!